# TODO!: compare with that PDF src also?
[vowels]
"अ" = "ɐ"
"आ" = "aː"
"इ" = "ɪ"
"ई" = "iː"
"उ" = "ʊ"
"ऊ" = "uː"
"ऋ" = "r̩"
"ॠ" = "r̩ː"
"ऌ" = "l̩"
"ॡ" = "l̩ː"
"ऎ" = "e"
"ए" = "eː"
"ऐ" = "ɑi" # wiki/Devanagari: ɑj, alternates on wiki/Help:IPA/Sanskrit: ɐːi̯; ai, ɐi or ɛi in Classical Sanskrit
"ऒ" = "o"
"ओ" = "oː"
"औ" = "ɑu" # wiki/Devanagari: ɑw, alternates on wiki/Help:IPA/Sanskrit: ɐːu̯; [au], [ɐu] or [ɔu] in Classical Sanskrit
"ऍ" = "æ"
"ऑ" = "ɒ"

[yogavaahas]
"ं" = "◌̃ " # TODO: difficulty copy-pasting. Encoding?
"ः" = "h"
"ᳵ" = "ẖ" # TODO:??
"ḫ" = "ᳶ" # TODO: ??
"ँ" = "◌̃ " # TODO: see above; comment on wiki/Help:IPA/Sanskrit: nasal vowel [ɐ̃], [ãː], [õː], etc.

[virama]
"्" = ""

[zwj]
"\u200d" = "{}"

[accents]
"॑" = "̭"
"॒" = "॒"
"᳡" = "̀"
"꣡" = "́"
"꣢" = "²"
"꣣" = "³"
"꣤" = "⁴"
"꣥" = "⁵"
"꣦" = "⁶"
"꣧" = "⁷"
"꣨" = "⁸"
"꣩" = "⁹"
"꣪" = "꣪"
"꣫" = "꣫"
"꣬" = "꣬"
"꣭" = "꣭"
"꣮" = "꣮"
"꣯" = "꣯"
"꣰" = "꣰"
"꣱" = "꣱"

[consonants]
"क" = "k"
"ख" = "kʰ"
"ग" = "g"
"घ" = "ɡʱ"
"ङ" = "ŋ"
"च" = "tɕ" # wiki/Help:IPA/Sanskrit: tɕ, wiki/Devanagari: tʃ
"छ" = "tɕʰ"
"ज" = "dʑ" # wiki/Help:IPA/Sanskrit: dʑ, wiki/Devanagari: dʒ
"झ" = "dʑʱ" # wiki/Help:IPA/Sanskrit: dʑʱ, wiki/Devanagari: dʒʱ
"ञ" = "ɲ"
"ट" = "ʈ"
"ठ" = "ʈʰ"
"ड" = "ɖ"
"ढ" = "ɖʱ"
"ण" = "ɳ"
"त" = "t" # wiki/Help:IPA/Sanskrit: t, wiki/Devanagari: t̪
"थ" = "tʰ" # wiki/Help:IPA/Sanskrit: tʰ, wiki/Devanagari: t̪ʰ
"द" = "d" # wiki/Help:IPA/Sanskrit: d, wiki/Devanagari: d̪
"ध" = "dʱ" # wiki/Help:IPA/Sanskrit: dʱ, wiki/Devanagari: d̪ʱ
# TODO!!: continue:
"न" = "n"
"प" = "p"
"फ" = "ph"
"ब" = "b"
"भ" = "bh"
"म" = "m"
"य" = "y"
"र" = "r"
"ल" = "l"
"व" = "v"
"श" = "ś"
"ष" = "ṣ"
"स" = "s"
"ह" = "h"
"ळ" = "ḷ"
"क्ष" = "kṣ"
"ज्ञ" = "jñ"

[symbols]
"०" = "0"
"१" = "1"
"२" = "2"
"३" = "3"
"४" = "4"
"५" = "5"
"६" = "6"
"७" = "7"
"८" = "8"
"९" = "9"
"ॐ" = "ōṁ"
"ऽ" = "'"
"।" = "।"
"॥" = "॥"

[extra_consonants]
"क़" = "q"
"ख़" = "k͟h"
"ग़" = "ġ"
"ज़" = "z"
"ड़" = "ṛ"
"ढ़" = "ṛh"
"फ़" = "f"
"य़" = "ẏ"
"ऱ" = "ṟ"
"ऴ" = "ḻ"
"ऩ" = "ṉ"
"ऱ्" = "r̆"
"थ़" = "s̱" # urdu ث, approximated by t
"स़" = "s̤" # urdu ص, approximated by s
"ह़" = "h̤" # urdu ح, approximated by h
"त़" = "t̤" # 
"झ़" = "ž"

"च़" = "ʦ" # used in kAshmIri and transliterated as ʦ by Grierson.
"छ़" = "ʦh" # used in kAshmIri and transliterated as ʦh by Grierson
"ذ" = "ẕ" # urdu ذ
"ض" = "ż"  # urdu ض "emphatic" /d/: pharyngealized voiced alveolar stop, lateral sides of tongue pressed to palate, front touching. Some urdu dicts use z̤.
"ظ" = "ẓ"  # urdu ظ  velarized voiced dental fricative.  Some urdu dicts use z̤.
"व़" = "w"  # urdu و, devanAgarI equivalent made up

[accented_vowel_alternates]
"á" = [ "á",]
"é" = [ "é",]
"í" = [ "í",]
"ó" = [ "ó",]
"ú" = [ "ú",]
"ŕ̥" = [ "ŕ̥",]
"à" = [ "à",]
"è" = [ "è",]
"ì" = [ "ì",]
"ò" = [ "ò",]
"ù" = [ "ù",]
"r̥̀" = [ "r̥̀",]

[alternates]
"|" = [ ".", "/",]
"||" = [ "..", "//",]
"'" = [ "`",]
"m̐" = [ "ṁ",]
"ṝ" = [ "ṝ", "r̥̄", "r̥̄", "ṝ", "ṝ",]
"ṃ" = ["ṃ"]
"ḥ" = ["ḥ"]
"ṭ" = ["ṭ"]
"ṭh" = ["ṭh"]
"ḍ" = ["ḍ"]
"ḍh" = ["ḍh"]
"ṇ" = ["ṇ"]
"ṅ" = ["ṅ"]
"ñ" = ["ñ"]
"ṣ" = ["ṣ"]
"ṛ" = [ "ṛ"]
"ṛh" = [ "ṛh"]
"k͟h" = [ "ḵẖ", "ḵh"] # shakespear urdu dict
"q" = ["ḳ"] # shakespear urdu dict
"w" = [ "ẉ"] # some urdu dicts
"ġ" = ["g̠ẖ"] # some urdu dicts
"́" = [ "¹",]
"r̥" = ["r̤i"] # Platts urud dict
