[vowels]
"अ" = "a"
"आ" = "a"
"इ" = "i"
"ई" = "ii"
"उ" = "u"
"ऊ" = "uu"
"ऋ" = ",r"
"ॠ" = ",rr"
"ऌ" = ",l"
"ॡ" = ",ll"
"ऎ" = "e"
"ए" = "ee"
"ऐ" = "ai"
"ऒ" = "o"
"ओ" = "oo"
"औ" = "au"
"ऍ" = "^e"
"ऑ" = "^o"

[yogavaahas]
"ं" = ";m"
"ः" = ".h"
"ᳵ" = "_h"
"ᳶ" = "^h" # TODO: flipped in iso - bug?
"ँ" = "~m"

[virama]
"्" = ""

[zwj]
"\u200d" = "{}"

[accents]
"॑" = "̭"
"॒" = "॒"
"᳡" = "̀"
"꣡" = "́"
"꣢" = "²"
"꣣" = "³"
"꣤" = "⁴"
"꣥" = "⁵"
"꣦" = "⁶"
"꣧" = "⁷"
"꣨" = "⁸"
"꣩" = "⁹"
"꣪" = "꣪"
"꣫" = "꣫"
"꣬" = "꣬"
"꣭" = "꣭"
"꣮" = "꣮"
"꣯" = "꣯"
"꣰" = "꣰"
"꣱" = "꣱"

[consonants]
"क" = "k"
"ख" = "kh"
"ग" = "g"
"घ" = "gh"
"ङ" = ";n"
"च" = "c"
"छ" = "ch"
"ज" = "j"
"झ" = "jh"
"ञ" = "~n"
"ट" = ".t"
"ठ" = ".th"
"ड" = ".d"
"ढ" = ".dh"
"ण" = ".n"
"त" = "t"
"थ" = "th"
"द" = "d"
"ध" = "dh"
"न" = "n"
"प" = "p"
"फ" = "ph"
"ब" = "b"
"भ" = "bh"
"म" = "m"
"य" = "y"
"र" = "r"
"ल" = "l"
"व" = "v"
"श" = ";s"
"ष" = ".s"
"स" = "s"
"ह" = "h"
"ळ" = ".l"
"क्ष" = "k.s"
"ज्ञ" = "j~n"

[symbols]
"०" = "0"
"१" = "1"
"२" = "2"
"३" = "3"
"४" = "4"
"५" = "5"
"६" = "6"
"७" = "7"
"८" = "8"
"९" = "9"
"ॐ" = "oo;m"
"ऽ" = "'"
"।" = "।"
"॥" = "॥"

[extra_consonants]
"क़" = "q"
"ख़" = "_kh"
"ग़" = ".g"
"ज़" = "z"
"ड़" = ".r"
"ढ़" = ".rh"
"फ़" = "f"
"य़" = ";"
"ऱ" = "_r"
"ऴ" = "_"
"ऩ" = "_n"
"ऱ्" = "^r"
# TODO: bug in iso? comment says t, but is s
"थ़" = "_t" # urdu ث, approximated by t
"स़" = ",t" # urdu ص, approximated by s
"ह़" = ",h" # urdu ح, approximated by h
"त़" = ",t" # 
"झ़" = "^z"

"च़" = "ts" # used in kAshmIri and transliterated as ʦ by Grierson.
"छ़" = "tsh" # used in kAshmIri and transliterated as ʦh by Grierson
"ذ" = "_z" # urdu ذ
"ض" = ";z"  # urdu ض "emphatic" /d/: pharyngealized voiced alveolar stop, lateral sides of tongue pressed to palate, front touching. Some urdu dicts use z̤.
"ظ" = ".z"  # urdu ظ  velarized voiced dental fricative.  Some urdu dicts use z̤.
"व़" = "w"  # urdu و, devanAgarI equivalent made up

[accented_vowel_alternates]
"á" = [ "á",]
"é" = [ "é",]
"í" = [ "í",]
"ó" = [ "ó",]
"ú" = [ "ú",]
"ŕ̥" = [ "ŕ̥",]
"à" = [ "à",]
"è" = [ "è",]
"ì" = [ "ì",]
"ò" = [ "ò",]
"ù" = [ "ù",]
"r̥̀" = [ "r̥̀",]

[alternates]
"|" = [ ".", "/",]
"||" = [ "..", "//",]
"'" = [ "`",]
"m̐" = [ "ṁ",]
"ṝ" = [ "ṝ", "r̥̄", "r̥̄", "ṝ", "ṝ",]
"ṃ" = ["ṃ"]
"ḥ" = ["ḥ"]
"ṭ" = ["ṭ"]
"ṭh" = ["ṭh"]
"ḍ" = ["ḍ"]
"ḍh" = ["ḍh"]
"ṇ" = ["ṇ"]
"ṅ" = ["ṅ"]
"ñ" = ["ñ"]
"ṣ" = ["ṣ"]
"ṛ" = [ "ṛ"]
"ṛh" = [ "ṛh"]
"k͟h" = [ "ḵẖ", "ḵh"] # shakespear urdu dict
"q" = ["ḳ"] # shakespear urdu dict
"w" = [ "ẉ"] # some urdu dicts
"ġ" = ["g̠ẖ"] # some urdu dicts
"́" = [ "¹",]
"r̥" = ["r̤i"] # Platts urud dict
